# Generated by Django 4.2.2 on 2023-07-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_teacher_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
    ]
