# Generated by Django 4.2.2 on 2023-07-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_courses_course_remove_teacher_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(upload_to='mainApp/static/images/'),
        ),
    ]
