# Generated by Django 4.2.2 on 2023-07-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_student_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='progamming_language',
            new_name='programming_language',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
